import streamlit as st
import cv2
import numpy as np
import pandas as pd
from PIL import Image
import io

# --- Import your backend logic functions ---
# Assuming your main.py file (with extract_marks_from_marksheet, calculate_total_marks, process_marksheet)
# is saved as 'marksheet_processor.py' in the same directory.
# If it's still named 'main.py', change the import accordingly: from main import extract_marks_from_marksheet, calculate_total_marks
from main import extract_marks_from_marksheet, calculate_total_marks # Assuming your original code is in main.py

# --- Streamlit UI ---
st.set_page_config(page_title="SmartGrade AI Marks Evaluator", layout="centered")
st.title("📚 SmartGrade AI: Automated Marksheet Evaluation")

st.write("Upload a marksheet image (JPG, PNG) to automatically extract marks and calculate totals.")

# Define configurable maximum scores
MAX_SCORE_PART_A_QUESTION = 3
MAX_SCORE_PART_B_QUESTION = 14

st.sidebar.header("Configuration")
st.sidebar.write("Set the maximum marks for each question type.")
part_a_max_input = st.sidebar.number_input(
    "Max Marks per Part A Question",
    min_value=1,
    max_value=20, # Arbitrary max, adjust as needed
    value=MAX_SCORE_PART_A_QUESTION,
    step=1
)
part_b_max_input = st.sidebar.number_input(
    "Max Marks per Part B Selected Question",
    min_value=1,
    max_value=50, # Arbitrary max, adjust as needed
    value=MAX_SCORE_PART_B_QUESTION,
    step=1
)

uploaded_file = st.file_uploader("Choose a marksheet image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Read the image from the uploaded file
    file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)
    original_image_cv2 = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)

    if original_image_cv2 is None:
        st.error("Error: Could not decode the image. Please ensure it's a valid image file.")
    else:
        st.image(original_image_cv2, caption="Uploaded Marksheet", use_column_width=True)
        st.write("")
        st.subheader("Processing Marksheet...")

        # Save the image temporarily to be processed by your existing function
        # This is a workaround as your function expects a file path.
        # In a more integrated solution, extract_marks_from_marksheet could directly accept a cv2 image.
        temp_image_path = "uploaded_marksheet_temp.jpg"
        cv2.imwrite(temp_image_path, original_image_cv2)

        # Process the marksheet using your existing functions
        # We need to adapt the `process_marksheet` or call its components directly
        # because Streamlit handles display, not `process_marksheet` printing.

        marks = extract_marks_from_marksheet(temp_image_path)
        
        if marks:
            part_a, part_b, total, pair_details = calculate_total_marks(
                marks, part_a_max_input, part_b_max_input
            )

            st.success("Marksheet processed successfully!")

            st.subheader("Extracted Marks and Calculation:")
            st.write("**Extracted Total Raw Marks per Question (from image, demo-corrected):**")
            st.json(marks) # Display marks as JSON for readability

            st.write(f"**Part A Marks (Compulsory, max {part_a_max_input} marks per question):** {part_a}")
            st.write(f"**Part B Marks (Max from pairs, max {part_b_max_input} marks per selected question):**")
            for detail in pair_details:
                st.write(f"  - {detail}")

            st.markdown("---")
            st.balloons() # Add some celebratory animation!
            st.header(f"Total Marks: {total} / {part_a_max_input * 10 + part_b_max_input * 5}") # Show total out of 100
            st.markdown("---")
            
            # Display the debug image generated by extract_marks_from_marksheet
            st.subheader("Debug Visualization (ROIs and Detected Marks):")
            debug_image_path = "mark_detection_debug.jpg"
            try:
                debug_image = cv2.imread(debug_image_path)
                if debug_image is not None:
                    st.image(debug_image, caption="ROI Detection Debug", use_column_width=True)
                else:
                    st.warning("Could not load debug image. Ensure 'mark_detection_debug.jpg' was created.")
            except Exception as e:
                st.error(f"Error loading debug image: {e}")
        else:
            st.error("Marks extraction failed. Please check the image or the extraction logic.")
            
else:
    st.info("Please upload an image file to begin evaluation.")